spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  error:
    include-message: always
    include-binding-errors: always